image: node:14.19.0

stages:
  - build
  - test
  - deploy

cache:
  key:
    files:
      - package-lock.json
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - npm install
    - npm run type:check

run_tests:
  stage: test
  needs:
    - install_dependencies
  script: npm run test

deploy_to_aws:
  stage: deploy
  variables:
    AWS_ACCESS_KEY_ID: "$AWS_ACCESS_KEY_ID"
    AWS_SECRET_ACCESS_KEY: "$AWS_SECRET_ACCESS_KEY"
  needs:
    - install_dependencies
    - run_tests
  script:
    - echo $AWS_ACCESS_KEY_ID
    - npm install -g serverless
    - sls deploy --stage prod