image: node:14.19.0

stages:
  - build
  - test
  - deploy

install_dependencies:
  stage: build
  script:
    - npm install
    - npm run type:check
  artifacts:
    paths:
      - node_modules

run_tests:
  stage: test
  needs:
    - install_dependencies
  script: npm run test